=== mugglmenzel/cloud-components-mapping/trunk/netTypeSpecifications/netTypeSpecification.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!--Generated by XML Authority-->

<!ELEMENT name (#PCDATA)>

<!ELEMENT extension EMPTY>

<!ATTLIST extension  name  CDATA  #REQUIRED
                      class CDATA  #REQUIRED >
<!ELEMENT extendable (extension*)>

<!ATTLIST extendable  class CDATA  #REQUIRED >
<!ELEMENT param EMPTY>

<!ATTLIST param  name  CDATA  #REQUIRED
                  value CDATA  #REQUIRED >
<!ELEMENT executable (param*)>

<!ATTLIST executable  class CDATA  #REQUIRED >
<!ELEMENT netTypeSpecification (extendable* , executable?)>

<!ATTLIST netTypeSpecification  name CDATA  #REQUIRED >

=== mugglmenzel/cloud-components-mapping/netTypeSpecifications/timedNet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE netTypeSpecification SYSTEM "netTypeSpecification.dtd">
<netTypeSpecification name="timedNet">
	<extendable class=".kernel.Net">
		<extension name="firingRule" class=".netElementExtensions.llNet.TimedNetRule"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Place">
		<extension name="marking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.NaturalNumber"/>
		<extension name="initialMarking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.NaturalNumber"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Arc">
		<extension name="inscription" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.NaturalNumber1"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Transition"> 
		<extension name="delay" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.IntValue"/> 
	</extendable> 
</netTypeSpecification>

=== mugglmenzel/cloud-components-mapping/trunk/netTypeSpecifications/BlackTokenNet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE netTypeSpecification SYSTEM "netTypeSpecification.dtd">
<netTypeSpecification name="BlackTokenNet">
	<extendable class="de.huberlin.informatik.pnk.kernel.Net">
		<extension name="firingRule" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.SimpleRule"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Place">
		<extension name="marking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.BlackToken"/>
		<extension name="initialMarking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.BlackToken"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Arc"> 
		<extension name="inscription" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.BlackToken"/> 
	</extendable> 
	<extendable class="de.huberlin.informatik.pnk.kernel.Transition"> 
	</extendable> 
</netTypeSpecification>

=== mugglmenzel/cloud-components-mapping/trunk/netTypeSpecifications/PTNet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE netTypeSpecification SYSTEM "netTypeSpecification.dtd">
<netTypeSpecification name="PTNet">
	<extendable class="de.huberlin.informatik.pnk.kernel.Net">
		<extension name="firingRule" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.SimpleRule"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Place">
		<extension name="marking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.NaturalNumber"/>
		<extension name="initialMarking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.NaturalNumber"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Transition"> 
	</extendable> 
	<extendable class="de.huberlin.informatik.pnk.kernel.Arc">
		<extension name="inscription" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.NaturalNumber1"/>
	</extendable>
</netTypeSpecification>

=== mugglmenzel/cloud-components-mapping/netTypeSpecifications/bagNet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE netTypeSpecification SYSTEM "netTypeSpecification.dtd">
<netTypeSpecification name="bagNet">
	<extendable class="de.huberlin.informatik.pnk.kernel.Net">
		<extension name="firingRule" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.SimpleRule"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Place">
                <extension name="tokenClass" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenClassName"/>
		<extension name="marking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenBag"/>
		<extension name="initialMarking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenBag"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Transition"> 
	</extendable> 
	<extendable class="de.huberlin.informatik.pnk.kernel.Arc">
                <extension name="tokenClass" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenClassName"/>
		<extension name="inscription" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenSet"/>
	</extendable>
</netTypeSpecification>

=== mugglmenzel/cloud-components-mapping/netTypeSpecifications/HLNet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE netTypeSpecification SYSTEM "netTypeSpecification.dtd">
<netTypeSpecification name="HLNet">
	<extendable class="de.huberlin.informatik.pnk.kernel.Net">
		<extension name="firingRule" class="de.huberlin.informatik.pnk.netElementExtensions.hlNet.HLRule"/>
		<extension name="signature" class="de.huberlin.informatik.pnk.netElementExtensions.hlNet.Signature"/>
		<extension name="declaration" class="de.huberlin.informatik.pnk.netElementExtensions.hlNet.Signature"/>
		<extension name="variables" class="de.huberlin.informatik.pnk.netElementExtensions.hlNet.Signature"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Place">
                <extension name="tokenClass" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenClassName"/>
		<extension name="marking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenSet"/>
		<extension name="initialMarking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenSet"/>
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Transition">
	</extendable>
	<extendable class="de.huberlin.informatik.pnk.kernel.Arc">
		<extension name="inscription" class="de.huberlin.informatik.pnk.netElementExtensions.hlNet.HLInscription"/>
	</extendable>
</netTypeSpecification>

=== mugglmenzel/cloud-components-mapping/trunk/netTypeSpecifications/subrange.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE netTypeSpecification SYSTEM "netTypeSpecification.dtd">
<netTypeSpecification name="subrange">
        <extendable class=".kernel.Net">
                <extension name="firingRule" class=".netElementExtensions.hlNet.HLRule"/>
                <extension name="signature" class="de.huberlin.informatik.pnk.netElementExtensions.hlNet.TestSig"/>
        </extendable>
        <extendable class="de.huberlin.informatik.pnk.kernel.Place">
                <extension name="tokenClass" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenClassName"/>
                 <extension name="marking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenSet"/> 
                <extension name="initialMarking" class="de.huberlin.informatik.pnk.netElementExtensions.llNet.TokenSet"/>
         </extendable>
        <extendable class="de.huberlin.informatik.pnk.kernel.Arc">
                <extension name="inscription" class="de.huberlin.informatik.pnk.netElementExtensions.hlNet.HLInscription"/>
        </extendable>
        <extendable class="de.huberlin.informatik.pnk.kernel.Transition">
        </extendable>
</netTypeSpecification>
